# Nightly scheduled 
name: Nightly run

# Controls when the workflow will run
on:
  schedule:
    # Run 5:30 am daily UTC
    - cron:  '30 5 * * *'
  workflow_dispatch:

# Run tests
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/test-grep.yml
    with:
      suite: 'both'
      environment: 'vpcstable'
      database: 'qa-conditions'
      grep: ''
      grepinvert: '@known_defect|@wip|@broken_test'
      uploadReport: true